affichageSDL : affichageSDL.o
	gcc -o affichageSDL affichageSDL.o -lSDL2 -lm -lSDL2_image -lSDL2_ttf

affichageSDL.o : affichageSDL.c
	gcc -c -Wall -Wextra affichageSDL.c -o affichageSDL.o -lSDL2 -lm -lSDL2_image -lSDL2_ttf

menuT : menuT.o
	gcc -o menuT menuT.o -lSDL2 -lm -lSDL2_image -lSDL2_ttf

menuT.o : menuT.c
	gcc -c -Wall -Wextra menuT.c -o menuT.o -lSDL2 -lm -lSDL2_image -lSDL2_ttf

